pip install peft
pip install bitsandbytes
pip install transformers==4.30
pip install accelerate
pip install sacrebleu
pip install datasets
pip install utils
pip install optuna
pip install 'ray[tune]'
pip install sigopt
pip install wandb
pip install bert_score
pip install rouge_score
pip install git+https://github.com/google-research/bleurt.git
pip install StringGenerator
pip install kss==3.7.3
pip install python-mecab-ko